### ISSUE TITLE
Can't use `d` in visual mode in Safari.

### ISSUE THREAD

**Issue by aaronrolls** [godbout/kindaVim.docs#103]
Perhaps I am missing something, but `d` will not remove text in visual mode in Safari. Below is a video of this happening in this very input box.

https://user-images.githubusercontent.com/47949221/181996358-28b41e3f-56fc-469c-b91b-93163aa4e5d7.mp4

It does work in other apps, so I am assuming it is a bug.

**Comment by godbout** [comment]
working fine here:

https://user-images.githubusercontent.com/121373/182006944-b339dd96-3e5d-4d00-a41a-db8efa00d394.mp4

**Comment by godbout** [comment]
any chance Safari is not in the `PG-R` Family?

**Comment by aaronrolls** [comment]
> any chance Safari is not in the PG-R Family?

Ah, that was it... I thought since it was native it would have been detected automatically. I feel dumb now.

**Comment by godbout** [comment]
https://user-images.githubusercontent.com/121373/182007017-8194a94c-3d7a-441c-8286-2fda1b00f4cb.mp4

**Comment by godbout** [comment]
> Ah, that was it... I thought since it was native it would have been detected automatically. I feel dumb now.

don't be so hard on yourself! Viming under macOS is hard.

even though some apps are native, you can't modify text with the AX APIs. and the AX APIs tell you that the modification succeeded... that happens mostly in some Catalyst apps, some Electron, and Safari (Safari is native yeah but it's still rendering web content).

there's some discussions here and there (at least [here](https://github.com/godbout/kindaVim.docs/discussions/48)) about whether built-in apps should be directly put into some `Families`. i'm not sure yet how to solve this conundrum. on the one hand i want kV to work straight out of the box, on the other hand someone who uses kV will have to deal with `Families` at one time. also, for some apps, you have different suggestions/Families, depending on how/which Vim moves you use yourself. so yeah, still need to digest before implementing something a bit better.
