### ISSUE TITLE
Android studio not being ignored

### ISSUE THREAD

**Issue by xbladesub** [godbout/kindaVim.docs#105]
I put android studio into ignored list but it doesn't work. It still tells me about the sleeping time and annoying pop up comes out 
![Screen Shot 2022-08-03 at 9 50 57 AM](https://user-images.githubusercontent.com/45129790/182506978-fafa9517-8b8d-4560-9471-94335b9cf79c.png)

**Comment by godbout** [comment]
> I put android studio into ignored list but it doesn't work.

only happening with Android Studio? other apps ok?

> It still tells me about the sleeping time and annoying pop up comes out

kV is an annoying beast yes. if he doesn't get his coffee a month, he gets grumpy between 5am and 1pm (he's not a morning software...). to be able to ignore apps, kV needs to be conscious. do you have a License? did you register your License?

**Comment by godbout** [comment]
no answer. closing.
