### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by krillin666** [godbout/kindaVim.docs#106]
Hey @godbout, this seems like an amazing app. Unfortunately, it is for mac only. 
I've searched but found no other alternative for Linux. Would porting this to Linux be a possibility for you ?

Thank you for your time !

**Comment by godbout** [comment]
am i dreaming or we already had this conversation? 😅️

kindaVim is literally rewriting Vim using macOS APIs. so it's macOS and that's it. no port possible, except if someone can magically bring macOS APIs AND technology under Linux. what you need to find is someone who's crazy enough to start this from scratch under Linux, using Linux APIs.

good luck!
