### ISSUE TITLE
Passthrough switching to insert mode & cursor appearance

### ISSUE THREAD

**Issue by jannis-baum** [godbout/kindaVim.docs#107]
> When pressing a key combination with a modifier key that has Passthrough enabled, kV switches to insert mode "leaving the selection in tact" as stated in the preferences.

Why does this happen? I personally can't really see any reason I would want this over just staying in whatever mode I was in.

If this is for some hard to avoid reason, would it be possible to not leave the selection in tact and instead switch to the bar cursor, i.e. do what would happen if I was to press `i` and then the key combination?

I frequently find myself in insert mode with one character selected, thinking I'm in normal mode. To me personally, it would be a lot more intuitive to force having no selection (i.e. the bar cursor) whenever I'm in insert mode and only ever allow a selection in normal mode (exactly one character) or visual mode.

---

On a somewhat unrelated and completely un-researched note: Do you know if it would be at all possible/feasible to not use a one-character-selection for the normal mode cursor and instead *draw* a transparent rectangle over where the cursor should be? I have no idea if you can get pixel positions for characters or if you can even freely draw transparent shapes, but if it is possible and feasible, I think it would be a really cool alternative to using the selection.

This would make it more clear what mode we're in based on only the cursor's appearance, we could customize the cursor color and have visual separation between selected text and the normal mode cursor (also useful for pressing `o` in visual mode, for example).

**Comment by godbout** [comment]
> Why does this happen? I personally can't really see any reason I would want this over just staying in whatever mode I was in.

there's two and a half reasons. i write them in order of priority:
1. many people want to be able to run macros on the selected text. (or the Alfred Universal Actions or whatever they're using.) there used to be a `Kill Switch` before, especially made for that, that would leave whatever mode and leave the selection intact. nothing else allowed you to leave Normal Mode except the Kill Switch, and one of the 10 motions allowed in Vim itself (see my second point). when i added the passthrough, it was then redundant, so i've removed it.
2. Vim itself only allows 10 moves to go back to Insert Mode: `.A, .a, .C, .c, .I, .i, .O, .o, .S, .s`. to me, that reinforces the first point. i wouldn't want to get bad habits that don't work in Vim itself. in Vim, the way to go back to Insert Mode are those motions, and if you're in Visual Mode, you need to switch back to Normal Mode first. that is the habit. the passthroughs are to let you interact with macOS, yes, but shouldn't be there to help develop bad habits.
2.5. there's no way to consistently leave Normal Mode and not leave the selection behind. i've tried, doesn't work. there's many cases that may happen (a click out of the window, a popup taking over, etc.) and where you lose access to the window, so there's no way to remove that selection. so you will always find cases where you're in Insert Mode and there's still selection. at least from my knowledge. there could probably be a way of storing all the windows of the OS, and when you get ejected from one you try to match it back, and force back the focus to it (huh?), etc, etc. mega nightmare. not even sure it's possible. would make kV way more complicated and easy to break, for virtually, at least to me, no much benefit.

> I frequently find myself in insert mode with one character selected, thinking I'm in normal mode. To me personally, it would be a lot more intuitive to force having no selection (i.e. the bar cursor) whenever I'm in insert mode and only ever allow a selection in normal mode (exactly one character) or visual mode.

are you aware of the Characters Window? there's the Vim Mode. you can see what mode you're in, and it can be shown right above the caret.

> On a somewhat unrelated and completely un-researched note: Do you know if it would be at all possible/feasible to not use a one-character-selection for the normal mode cursor and instead _draw_ a transparent rectangle over where the cursor should be? I have no idea if you can get pixel positions for characters or if you can even freely draw transparent shapes, but if it is possible and feasible, I think it would be a really cool alternative to using the selection.
> 
> This would make it more clear what mode we're in based on only the cursor's appearance, we could customize the cursor color and have visual separation between selected text and the normal mode cursor (also useful for pressing `o` in visual mode, for example).

yeah i know people like to use different carets for different modes. i had a look in the past. it's heavy. you can get the caret bounds yes (that's what i use for showing the Characters Window above the caret). the rest is not straightforward. draw something, **get rid of the OS caret**, which color works in all cases? none. so you need to record pixels and adjust for proper contrast. the list keeps going. the current way is just way too good in terms of functionality/balance. so the custom caret is currently way down the list of priority (way way down). for the two stuff you mentioned today (already forgot what the other one was sorry 😅️), it requires a lot of work, lot of hacks, and that will make kV more frail. definitely not looking forward to this. kV is already complicated enough.

**Comment by godbout** [comment]
> are you aware of the Characters Window? there's the Vim Mode. you can see what mode you're in, and it can be shown right above the caret.

https://user-images.githubusercontent.com/121373/182634156-fa3417a3-0e7a-4c9d-b24f-ee44bd20fc29.mp4

this shows you the Mode: `I`, `N`, `v`, `V` and also if you're in operator pending mode by adding `[]`. (in the video sometimes the Characters Window disappear when it shouldn't. it's a bug in Ventura.)

**Comment by jannis-baum** [comment]
Thanks a lot for always putting so much effort and giving such detailed explanations! I really appreciate that and already got to learn a lot from it!

I'll move my Characters Window to above the caret like you suggested, that should do it☺️ I would close this as not planned now with the explanations you gave in your first response but I'll leave it up to you to decide what to do with the issue.

**Comment by godbout** [comment]
> Thanks a lot for always putting so much effort and giving such detailed explanations! I really appreciate that and already got to learn a lot from it!

of course. everybody deserves an answer. even those sorts of questions: #90. although the level of troll may vary 😂️

thing is, like i said in the other thread, i want(ed) kV to be straightforward, but the nature of the project makes it less than i'm happy with it. but nothing much i can do. so there's the `Families`, there's the "enforcing the Keyboard Strategy", there's this thing of passthrough, etc, etc. stuff are still evolving. but one thing for sure is that A LOT of what you see or experience in kV is a deliberate decision, to solve some sort of problems. now for sure i've missed stuff, or for some stuff i may have made a wrong choice. which is why it's great when people ask thoughtful questions or start thoughtful debates because it helps me thinking things through again, and confirming (or the opposite) the current state of affairs. so please, feel free. the best thing that can come up from those questions is me finding that i cannot think of an answer, which would mean there's a hole somewhere that can be patched. and that would ultimately make kV better.

> I'll move my Characters Window to above the caret like you suggested, that should do it☺️ I would close this as not planned now with the explanations you gave in your first response but I'll leave it up to you to decide what to do with the issue.

let me know how it goes once you've used it for a few days. personally i keep it at the caret too, but i use the Vim Move instead.

**Comment by godbout** [comment]
oh btw, there's another possible way for you to know whether you're in Insert Mode (normal macOS) or stuck in kV Normal/Visual Mode. you could highlight the window that is Viming. if you're not in fullscreen, kV will fade out all the other windows. if you're in fullscreen, it will add layer on top of your app. personally i'm using this since day and find it very helpful (that's why i built it in the first place):

https://user-images.githubusercontent.com/121373/183005675-f974b8ee-0260-44fc-b38f-b2b2d2ec4d86.mp4

**Comment by godbout** [comment]
> I would close this as not planned now with the explanations you gave in your first response but I'll leave it up to you to decide what to do with the issue.

gonna close for now yes. the custom cursor, if it comes, may come way later. maybe now that there are the Distributed Notifications, something can be done through other tools? no idea.
