### ISSUE TITLE
add Element.app

### ISSUE THREAD

**Issue by xbladesub** [godbout/kindaVim.docs#109]
Doesn't seem to work correctly. This messenger becomes more popular day by day

**Comment by godbout** [comment]
will add for next release. thanks.

**Comment by godbout** [comment]
@xbladesub added for the next release. for the time being, add Element to the `Key Mapping` Family. Element is an Electron app that doesn't handle the macOS Accessibility, so you need key remapping. once it's in the `Key Mapping` Family it'll be consistent, and the copying the deleted/changed text is pasted correctly to the macOS clipboard.
