### ISSUE TITLE
Unsubscribing

### ISSUE THREAD

**Issue by benji-york** [godbout/kindaVim.docs#121]
I've decided that kindaVim isn't for me, but after scouring the site I can't find a way to unsubscribe.  How do I do that?

**Comment by godbout** [comment]
unsubscribing is not available yet and will probably be implemented only next year ☹️

ok, kidding. sorry to see you go! please feel free to send feedback if you want.

the page to cancel your subscription is available from within kindaVim:

![Screenshot 2022-08-25 at 01 58 29](https://user-images.githubusercontent.com/121373/186490475-a8575b52-de2c-408b-beaf-20758e397cbd.png)

you'll be sent to the secure page with your email prefilled. you just need to enter your Order Number. (if you don't have it, click the `Recover Orders` in kindaVim and you'll receive your info by email.)

once you submit the form you'll get the Paddle stuff that allows you to cancel your sub.

let me know. if you don't wanna bother then i can also cancel it for you.

**Comment by benji-york** [comment]
Thanks for the quick and thorough response and best of luck on the project!

**Comment by godbout** [comment]
thank you! my pleasure. thanks for having been an early supporter. and sorry that it didn't fulfill your needs.
