### ISSUE TITLE
add Adobe Illustrator 2022.app

### ISSUE THREAD

**Issue by albert-ying** [godbout/kindaVim.docs#126]

**Comment by godbout** [comment]
will check, thanks.

**Comment by godbout** [comment]
seems it's gonna be a pain to test, coz just a 7 day trial that requires cc. @albert-ying can you confirm that this is the version you're using? https://www.adobe.com/products/illustrator/free-trial-download.html

thanks.

**Comment by albert-ying** [comment]
Yes, it is, thank you so much.
Best,
Albert

**Comment by godbout** [comment]
installed it. not sure what's you're expectation about using kV with Illustrator? coz, i'm pretty sure that for those apps you wanna use the mouse 😅️

https://user-images.githubusercontent.com/121373/193099394-4f303bd4-6602-4c03-82d8-1696d9e39bb4.mp4

let me know and i'll add something in The Wizard for the next release (soon).

**Comment by godbout** [comment]
trial is 7 days. i will have to cancel it tomorrow. any news @albert-ying?

**Comment by godbout** [comment]
@albert-ying did you watch the video? it seems all good to me. so i'm not sure what you mean by "the text box". can you get a video, or at least a screenshot? thanks.

**Comment by albert-ying** [comment]
Here -- it appears when you click `T` type tool and drag a text box

<img width="917" alt="image" src="https://user-images.githubusercontent.com/59846322/193883180-cf2011e1-b910-4e1b-bba9-fba3cbe2ea46.png">

**Comment by godbout** [comment]
> Here -- it appears when you click `T` type tool and drag a text box
> 
> <img alt="image" width="917" src="https://user-images.githubusercontent.com/59846322/193883180-cf2011e1-b910-4e1b-bba9-fba3cbe2ea46.png">

ok, thanks.

so yeah, this part of the app, it's completely custom UI. we can't do anything unfortunately. the rest of the app seems to be working fine in Auto. sometimes kV can use the Accessibility Strategy. when it cannot it switches to the Keyboard Strategy. seems to be working quite well.

**Comment by albert-ying** [comment]
Haha, the text box. Sometimes I need to type a paragraph alongside the
figure.
Best,
Albert

**Comment by godbout** [comment]
> Haha, the text box. Sometimes I need to type a paragraph alongside the figure. Best, Albert
> […](#)

well i guess here's your email...

**Comment by albert-ying** [comment]
sorry, the email is now traveling so slow, lol -- what you said is reasonable, I will close this. Thank you for looking into it!

**Comment by godbout** [comment]
my pleasure. sorry we can't do more!
