### ISSUE TITLE
`gU`/`gu` to change to uppercase/lowercase

### ISSUE THREAD

**Issue by agbohub** [godbout/kindaVim.docs#134]
kindaVim 42 supports `~` to switch case but not yet `gU`/`gu` to change to uppercase/lowercase.

**Comment by godbout** [comment]
yep. never requested, and i don't use them myself, so never done. thanks for requesting. will add.

**Comment by godbout** [comment]
wow ok, so i've been checking and i hadn't realized that this will take a motion as a parameter. that will make the thing way more complicated and that means i need to test and implement moves one by one. so, which ones are you using? so that i do those ones first.

thanks.

**Comment by agbohub** [comment]
Thanks! Actually, to simplify things, it would be good enough for the vast majority of "cases" if I can use `U`/`u` to switch selected words in visual mode to uppercase/lowercase ;)

**Comment by godbout** [comment]
oh. nice. that is going to be MUCH EASIER to do. there'a also already the Visual Mode `~`, if that helps.
i'll try to squeeze this in the next release (should happen within a few days).

**Comment by godbout** [comment]
added in kV43: https://github.com/godbout/kindaVim.docs/releases/tag/43

if you're fine with this, let's close this issue. i want to forget about the `gU/gu` 😂️

**Comment by agbohub** [comment]
Fair enough! Issue closed 😝
