### ISSUE TITLE
add Vimac

### ISSUE THREAD

**Issue by tim0120** [godbout/kindaVim.docs#141]

**Comment by godbout** [comment]
i do not allow the competition.

**Comment by tim0120** [comment]
I think I was confused about the functionality of kV when I posted this, sorry!

**Comment by godbout** [comment]
no worries. i'll still add it.

**Comment by godbout** [comment]
i'll close this issue when it's added, in the next release.

also, maybe you were mixing things up with Wooshy? https://github.com/godbout/Wooshy.docs
Wooshy has the same system where you can request support if it doesn't work on an app. i'll check if Vimac is supported (should be).

**Comment by godbout** [comment]
thanks!

kV and Wooshy are both paid apps, but there's free alternatives. you can check out the alternatives at the bottom of each repo's README. enjoy.

**Comment by godbout** [comment]
added in kV45: https://github.com/godbout/kindaVim.docs/releases/tag/45
