### ISSUE TITLE
Add option to hide menu bar icon?

### ISSUE THREAD

**Issue by johnaaron-git** [godbout/kindaVim.docs#144]
Hello, would it be possible to add a toggle to hide the KindaVIM and Wooshy menu bar icons?

I don't think there'd be any loss of functionality, since opening the apps through launchpad or Applications still shows their settings window.

Thank you :)

**Comment by godbout** [comment]
definitely doable. i personally use Bartender so i didn't bother. but can add. thanks!

**Comment by zeekay** [comment]
Would second this, I do like to keep the native menu bar minimal.

**Comment by godbout** [comment]
> Would second this, I do like to keep the native menu bar minimal.

ok good to know, i'll higher the priority then. but i still find it strange that some people who like their menu bar minimal (like me) don't use any tool like Bartender?

**Comment by godbout** [comment]
done 👀️🙈️: https://github.com/godbout/kindaVim.docs/releases/tag/62
