### ISSUE TITLE
add IntelliJ IDEA CE

### ISSUE THREAD

**Issue by AndreKucharzyk** [godbout/kindaVim.docs#145]
Please add support for IntelliJ IDEA CE

**Comment by godbout** [comment]
why using kV? i'll have a look, but as far as i remember when trying all the other JetBrains tools 1) they don't implement the macOS AX APIs 2) they have their own Vim taking care of their own products: https://www.jetbrains.com/help/idea/using-product-as-the-vim-editor.html

so what's the point of using kV there? 🤔️

**Comment by AndreKucharzyk** [comment]
Im just enjoying kV as it, so no additional layer of setting things up is always welcome, but I get what you are saying.

**Comment by godbout** [comment]
> so no additional layer of setting things up is always welcome

for sure. thing is, kV requires A LOT of info from macOS/the apps to be able to do its work properly. with native apps, all the AX info is handled by macOS itself and comes free out of the box. for custom shits, apps have to implement the stuff. most don't. Electron is shit. custom buffer rendering etc. like Sublime Text, JetBrains IDEs etc. are also most of the time out of reach. but that makes sense, they need to control their own buffer and UI to be able to have a proper IDE. in those cases, it's always better to use the Vim plugins that read and work on those buffers.

i've added a blah blah in The Wizard for IntelliJ. i'll make the blah blah link directly to the IdeaVim plugin (if possible).

**Comment by godbout** [comment]
added in kV46: https://github.com/godbout/kindaVim.docs/releases/tag/46

**Comment by AndreKucharzyk** [comment]
I appreciate it!
