### ISSUE TITLE
add Studio 3T.app

### ISSUE THREAD

**Issue by porfur** [godbout/kindaVim.docs#148]

**Comment by godbout** [comment]
will investigate. thanks.

**Comment by godbout** [comment]
any particular place where you're seeing any specific issue?

i haven't created a mongo database but i'm playing around the UI and it seems to be working out of the box. maybe it's different when you deal with the db and its data?

**Comment by godbout** [comment]
tested. Java app. which means it doesn't handle the macOS Accessibility properly, and also it doesn't respect macOS standard keyboard shortcuts. so good luck 😅️

out of the box kV will work expect when multilines are separated by the poor Java linefeed style.

**Comment by godbout** [comment]
added in kV47: https://github.com/godbout/kindaVim.docs/releases/tag/47
