### ISSUE TITLE
Not receiving an email for my new license.

### ISSUE THREAD

**Issue by jasonhawkharris** [godbout/kindaVim.docs#149]
I don't know where else to put this because I don't see any other support categories. I've attempted to refetch the order many times but it's been over an hour and I haven't received an email. Please advise.

**Comment by godbout** [comment]
fuck, sorry about this. gonna check right away.

**Comment by godbout** [comment]
ok, seems you (and i) got unlucky: https://paddle.status.io

Paddle is kV's payment provider and handles the Licenses emails, order emails etc. they're currently having outages ☹️
i'm gonna try to send you your License manually if i can, or send you a temporary one for now. back to you soon.

**Comment by godbout** [comment]
ok, you should have received my own email from my own server with your License now. ultimately you can always recover everything (and cancel) from within the kV's License Pane in the Preferences/Settings. that will send you to the kindavim.app site where you fill a form and get emails with your info.

the links kV will be sending you to are:
* recover your License: https://kindavim.app/recover
* manage your License (update payment or cancel sub): https://kindavim.app/manage

for both forms you need one of your Order #, but of course in your case you've never received the Paddle email. there's also a button in the License Pane of kV to get an email with all of your Order #s, but again this is sent by Paddle and they're broken now 😅️

anyways, hope this explains a bit. and sorry again for the trouble. not cool. please lemme know if you got the License email from my own server. i've checked from my email queue and everything went well and is sent, but please do let me know. thanks.

**Comment by jasonhawkharris** [comment]
All good now! Thank you for taking care of it. I appreciate it! This can be closed. 😎

**Comment by godbout** [comment]
> All good now! Thank you for taking care of it. I appreciate it! This can be closed. 😎

of course. that's why i'm here! enjoy.
