### ISSUE TITLE
Feature request: Custom keybindings

### ISSUE THREAD

**Issue by Alex23rodriguez** [godbout/kindaVim.docs#153]
Maybe I'm missing something but I didn't see a way to edit the default keybindings. I use a different keyboard layout so it's always the first thing I do when using vim, because the default keys (specially `hjkl`) can be hard to reach.

Any way this could be added? Thanks!

**Comment by godbout** [comment]
there's been many approaches thought. it's huge work to handle the custom bindings in kV itself. it's a huge work also to read a .vimrc. so the current best solution is using [Karabiner-Elements](https://karabiner-elements.pqrs.org) with the kV's [Distributed Notifications](https://github.com/godbout/kindaVim.docs#apis). with that combination you can remap keys **on a Mode basis**. like you could have keys acting in one way when you're in Normal Mode and in another way when you're in Visual Mode.

have a look at the discussion about this: https://github.com/godbout/kindaVim.docs/discussions/117

i think this is what you're looking for. lemme know in any case what you think and if it does help.

**Comment by Alex23rodriguez** [comment]
I see... I already have Karabiner-Elements, but not Hammerspoon as the post also suggests... I understand that the effort to implement keybindings directly on the app preferences might not be worth it, so i'll have to check if the same applies to me implementing this workaround xD
That being said, thanks for pointing me to a possible solution. I'll go ahead and close the issue

**Comment by godbout** [comment]
@Alex23rodriguez yeah, Hammerspoon is gonna be useful to catch the **Distributed Notifications** sent by kV to macOS. once you catch them, you will be able to call Karabiner-Elements and do basically whatever you want. this is way more flexible than having an inner custom keybindings, as you can even bind different mappings according to different apps! give it a try, i think you'll not be disappointed. feel free to ping me again if you need help.
