### ISSUE TITLE
add Spark Desktop.app

### ISSUE THREAD

**Issue by stephaneliu** [godbout/kindaVim.docs#158]
Vim motion 'w' and 'b' moves one character at a time.

'x' deletes the character on the left of (behind) the cursor
'dw' deletes one character on the left of (behind) the cursor

**Comment by godbout** [comment]
interesting. `Spark` is in kV's App Catalog:

<img width="675" alt="Screenshot 2023-01-23 at 16 16 58" src="https://user-images.githubusercontent.com/121373/213993200-ab4637d6-a400-444b-be00-6913eb6673f5.png">

seems there's a new Spark that is an Electron app? will check. if moves don't work even when you add that new Spark in the Key Mapping Family, that means the Accessibility Support is really bad, and the app needs to be pushed to the 911 Family (last resort). lemme know how it goes.

**Comment by stephaneliu** [comment]
You're right. The new Spark is called Spark Desktop. I didn't realize it's an electron app.

**Comment by godbout** [comment]
i'm just guessing. their marketing says it's a cross-platform app, so the most probable choice would be Electron. some apps are doing extra effort to support the macOS Accessibility, but most of them don't bother at all. will investigate and let you know soon.

**Comment by stephaneliu** [comment]
![Screenshot 2023-01-22 at 10 23 53 PM](https://user-images.githubusercontent.com/64043/213994166-544b5528-8b2a-4587-86b7-31fe29e698e4.png)

Dragging it in the Key Mapping worked! Thanks for your help. I didn't realize that Keyboard Strategy is a tab. I just installed it this morning.

**Comment by godbout** [comment]
> Dragging it in the Key Mapping worked! Thanks for your help.

great. no worries. i'll add Spark Desktop to the App Catalog, so for the next users an explanation and advise will show up in The Wizard.

> I didn't realize that Keyboard Strategy is a tab.

yeah, that could be better. usually if the app is in the App Catalog, you would just have to click the advise (button) and kV would add the app for you. SwiftUI is not yet fully ready for prod, so you can't add tabs in Settings panes. had to find a rather not-too-evil solution for now... but yeah. needs improvements. thanks.

**Comment by godbout** [comment]
added to App Catalog. will show up in kV 48.
