### ISSUE TITLE
add WebStorm

### ISSUE THREAD

**Issue by JoharyNyAina** [godbout/kindaVim.docs#159]

**Comment by godbout** [comment]
WebStorm is in kV's App Catalog, which means it has been tested and you're getting a description in The Wizard:

<img width="766" alt="Screenshot 2023-01-31 at 22 16 48" src="https://user-images.githubusercontent.com/121373/215784908-c9c00095-919e-42be-9473-7c3829fa3c89.png">

in JetBrains' tools, the buffer is not accessible through the macOS AX APIs. but they provide their own Vim plugin that uses their own buffer. so you better use this. link is in The Wizard's description. good luck!
