### ISSUE TITLE
add DEVONthink 3

### ISSUE THREAD

**Issue by yuvalgavish** [godbout/kindaVim.docs#171]

**Comment by godbout** [comment]
will add for the next kV release (beginning of May). first investigations show that kV supports DEVONthink 3 out of the box. please report if you're encountering any issue yourself. DEVONthink and Mellel seem to be quite some niche tools and i'm sure i'm only scratching the surface.

**Comment by godbout** [comment]
added in kV52: https://github.com/godbout/kindaVim.docs/releases/tag/52
