### ISSUE TITLE
add Rider

### ISSUE THREAD

**Issue by ethanfischer** [godbout/kindaVim.docs#175]
For the most part, things are working well. However, when the Intellisense menu comes up and hit my shortcut to enable kindaVim, it closes the Intellisense menu. I want to be able to scroll down the suggestions menu using j and k but this issue prevents that

**Comment by godbout** [comment]
checking.

**Comment by godbout** [comment]
ok, so a few things:
1. usually for JetBrains products i recommend using the native Vim plugin. see below. but that means that you have to disable kV for Rider, and you therefore can't use kV in menus.
<img width="410" alt="Screenshot 2023-05-12 at 16 46 59" src="https://github.com/godbout/kindaVim.docs/assets/121373/171da47d-fba0-42b8-82d4-af25f3c253cb">
2. which menus are you talking about? macOS one for Rider? own Rider internal menus? autocompletion?

**Comment by godbout** [comment]
alright, thanks. setting up my new workstation tonight (😍️) and then i'll have a closer look in the following days. but i would expect that the "autocompletion" is just some sort of custom UI and we can't do much about it. but will investigate and confirm.

**Comment by ethanfischer** [comment]
Okay thank you! Enjoy your new machine

**Comment by godbout** [comment]
yeah, it's a custom UI. as soon as you do something, it's gonna disappear. when you enter Normal Mode with kV, it's gonna select a character, so the custom UI will disappear. i think even if kV wouldn't select a character, Rider would probably behave the same. this is not a real UI Element. you can still go up and down with the macOS standard `CTRL n` `CTRL p` tho.

**Comment by ethanfischer** [comment]
Ah, alright. Well thank you for looking into it. I did not know about macOS
standard CTRL N CTRL P! That's a game changer and way better than arrow
keys, so thank you

-Ethan

**Comment by godbout** [comment]
macOS is following Emacs moves/standards. you may find a list of "useful" shortcuts here: https://support.apple.com/en-us/HT201236

but yeah it's Emacs. it sucks 😂️

**Comment by godbout** [comment]
@ethanfischer quick question: how do you use both the Rider Vim plugin, and kV? do you enter Normal Mode using two different sets of key? one for the IDEA plugin, and one for kV?

**Comment by ethanfischer** [comment]
Yeah I'm using the custom binding in kVim (Ctrl+;)

**Comment by godbout** [comment]
added in kV52: https://github.com/godbout/kindaVim.docs/releases/tag/52

**Comment by godbout** [comment]
JetBrains products descriptions have all been updated in kV53 to reflect the fact that you can use both the IdeaVim plugin for source code, and kV for the IDEs' UI: https://github.com/godbout/kindaVim.docs/releases/tag/53
