### ISSUE TITLE
add UpNote.app

### ISSUE THREAD

**Issue by gordonbazeley** [godbout/kindaVim.docs#176]
Please support this note taking app - [UpNote](https://getupnote.com/). It's Electron but the developer is very active and generally responsive to feature requests if that's what's needed to get support at support@getupnote.com

**Comment by godbout** [comment]
will check, thanks. Electron apps are tough. that's inherent to not going native. you have to manually handle all the Accessibility, while if you build native you have everything correct out of the box. from all the Electron apps that are supported i think the only one who is very close to native is Logseq. the rest, devs usually don't bother. i'll investigate soon and reach out if necessary.

**Comment by godbout** [comment]
added in kV52: https://github.com/godbout/kindaVim.docs/releases/tag/52
