### ISSUE TITLE
Install via Nix package manager

### ISSUE THREAD

**Issue by mrjones2014** [godbout/kindaVim.docs#178]
I consider kindaVim an absolutely essential app for macOS at this point, so thanks.

I'd like to install it via my `home-manager` config using Nix package manager.

Basically all that's needed is a static link to the latest release, and an SHA-256 hash of the zip that would be downloaded (so that Nix can verify that the correct thing was downloaded and not like some malware or something).

If I can just get that URL, I can at the very least write a custom derivation in my config, and in an ideal scenario, write a PR to [nixpkgs](https://github.com/NixOS/nixpkgs) so other people can also install it via Nix.

**Comment by godbout** [comment]
hair keeps growing!

the URL:

https://kindavim.app/releases/kindaVim.zip

always pointing to the latest version of kV. will check if there's "better" way to do a Nix native install.

**Comment by godbout** [comment]
closing coz not blocking, and not planning at all for now.
