### ISSUE TITLE
add WebStorm.app

### ISSUE THREAD

**Issue by Josh-Piper** [godbout/kindaVim.docs#181]
Can see you added IntelliJ, would love for other IDEs to also be supported

**Comment by godbout** [comment]
<img width="637" alt="Screenshot 2023-06-15 at 12 22 17" src="https://github.com/godbout/kindaVim.docs/assets/121373/c60294ae-c142-40ec-b718-18e47c52dab0">

WebStorm has been in for a while. any special version you're using?

**Comment by godbout** [comment]
> <img alt="Screenshot 2023-06-15 at 12 22 17" width="637" src="https://user-images.githubusercontent.com/121373/245992725-c60294ae-c142-40ec-b718-18e47c52dab0.png">
> WebStorm has been in for a while. any special version you're using?

actually that description was until kV52. it's been updated in 53:
![Screenshot 2023-06-15 at 12 35 37](https://github.com/godbout/kindaVim.docs/assets/121373/ce62f6c3-151c-4d2f-8c63-de14d89f5e89)

**Comment by Josh-Piper** [comment]
<img width="650" alt="Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 44 06@2x" src="https://github.com/godbout/kindaVim.docs/assets/35862340/fa1e2f73-9fb0-47de-9fee-ba5057975317">
<img width="273" alt="Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 44 30@2x" src="https://github.com/godbout/kindaVim.docs/assets/35862340/356fc125-5a59-49e6-87b2-f480b21e6572">
<img width="455" alt="Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 49 46@2x" src="https://github.com/godbout/kindaVim.docs/assets/35862340/34641108-56f8-4579-8f74-19fceeaa7317">


Weird that I am on version 53 but am receiving a different description. My installation is from the Jetbrains Toolbox. 

I am trying to click the breadcrumb from the status bar in Webstorm to navigate to a parent tag/function
![Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 48 05@2x](https://github.com/godbout/kindaVim.docs/assets/35862340/24c52081-fe67-4a19-abd3-5d337e966f3a)

**Comment by godbout** [comment]
> Weird that I am on version 53 but am receiving a different description. My installation is from the Jetbrains Toolbox.

interesting. didn't know about JetBrains Toolbox. so probably the bundle IDs are different, which is why the description is empty. i'll check, thanks.

> I am trying to click the breadcrumb from the status bar in Webstorm to navigate to a parent tag/function ![Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 48 05@2x](https://user-images.githubusercontent.com/35862340/246283693-24c52081-fe67-4a19-abd3-5d337e966f3a.png)
> 
> --- update --- Actually I can see the correct message when clicking on kindaVim after having my focus on Webstorm and then clicking the "Not Working Well with Webstorm" button. Just reliesed this issue is actually related to Wooshy and not kV...

yeah, i'm getting confused here 😂️
to click stuff, you don't use kV, you use Wooshy. with kV you get Vim moves in text, and some UI like menus, lists, etc. but you can't go "click" somewhere.

can you open an issue on the Wooshy's repo for that and i'll check. thanks.

**Comment by godbout** [comment]
> <img alt="Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 44 06@2x" width="650" src="https://user-images.githubusercontent.com/35862340/246283165-fa1e2f73-9fb0-47de-9fee-ba5057975317.png"> <img alt="Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 44 30@2x" width="273" src="https://user-images.githubusercontent.com/35862340/246283213-356fc125-5a59-49e6-87b2-f480b21e6572.png"> <img alt="Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-16 at 10 49 46@2x" width="455" src="https://user-images.githubusercontent.com/35862340/246283756-34641108-56f8-4579-8f74-19fceeaa7317.png">
> Weird that I am on version 53 but am receiving a different description. My installation is from the Jetbrains Toolbox.

getting the proper Wizard desc for WebStorm even if installed through JetBrain Toolbox. see video below:

https://github.com/godbout/kindaVim.docs/assets/121373/b60dd609-b88b-43aa-9266-13ac45943dfd

have you installed like a Developer Edition or something like that? can you get the Bundle ID of your WebStorm so that i can see why it doesn't match with kV's AppCatalog. thanks.

https://stackoverflow.com/questions/39464668/how-to-get-bundle-id-of-mac-application

**Comment by Josh-Piper** [comment]
`com.jetbrains.toolbox.linkapp.pcom.jetbrains.toolbox__eb_torm_2023_1_2`.
I dragged the application into the application input box in KindaVim instead of going through the menubar "Not Working Well with Webstorm".

I do get the correct message when I use the menubar item.

**Comment by godbout** [comment]
yeah i'm getting the same. but they're encoding THE RELEASE DATE in the Bundle ID. that means that i would need to update my whole AppCatalog every time they release a new version. the Bundle ID is supposed to be a constant string that represent your app. why they do that no fucking idea, but i'm not gonna support 😂️ i'm usually very flexible but this is utter bullshit.

**Comment by godbout** [comment]
not gonna handle that special case.
