### ISSUE TITLE
add Nota

### ISSUE THREAD

**Issue by mk1123** [godbout/kindaVim.docs#191]
thank you :)

**Comment by godbout** [comment]
seems it's on a waiting list? any `.app` somewhere so that i can do the investigation? thanks.

**Comment by godbout** [comment]
ok got a binary. seems the first investigation shows `Nota` should go to the `Keyboard Strategy`.

**Comment by godbout** [comment]
added in kV56: https://github.com/godbout/kindaVim.docs/releases/tag/56
