### ISSUE TITLE
Wizard text explanation cuts off when it is too long

### ISSUE THREAD

**Issue by codeluggage** [godbout/kindaVim.docs#195]
Only seen this with the Wizard for Discord so far, I think. Here's a screenshot: 
![image](https://github.com/godbout/kindaVim.docs/assets/1154150/71af65c4-8a07-4650-b6c9-5594ec5f19e9)

Not high priority in any way, but I do wonder what the rest of it said :D

My system:
- MacOS Sonoma: `14.0 Beta (23A5312d)`
- kV56

**Comment by godbout** [comment]
yeah, very fair. it's not supposed to happen in the sense that i check the desc length myself. not sure why i missed this one? anyways wait a sec. will bring it up.

**Comment by godbout** [comment]
"Electron app. There's two issues with Discord. It doesn't implement the writing part of the macOS Accessibility, so you need to add it to Key Mapping. But it also doesn't select text when using `shift control a` and `shift control e`, used by the Keyboard Strategy to generate moves. So some moves will not work properly. Both issues have been reported."

LOL. almost there.

**Comment by godbout** [comment]
oh i think i know the issue. spacing changed in the Markdown rendering of `code` in SwiftUI. so some parts of the desc take more width now. nice. no wonder i need to work on this full time 😂️

will update. thanks for reporting.

**Comment by godbout** [comment]
fixed in kV57: https://github.com/godbout/kindaVim.docs/releases/tag/57
