### ISSUE TITLE
add Smultron

### ISSUE THREAD

**Issue by danny-su** [godbout/kindaVim.docs#198]
add Smultron

**Comment by godbout** [comment]
will do. thanks!

**Comment by danny-su** [comment]
@godbout Does kindavim support ndd command, such as 3dd? I found only dd works.

**Comment by godbout** [comment]
> @godbout Does kindavim support ndd command, such as 3dd? I found only dd works.

you can see the current implementation in the README: https://github.com/godbout/kindaVim.docs#current-vim-implementation

every single move has to be recreated from scratch, including the `repeat` and the `count`. some are not done yet, but requests are welcome: https://github.com/godbout/kindaVim.docs/issues/139

you can see specifically what has been implemented for the [Accessibility Strategy](https://github.com/godbout/kindaVim.docs/blob/master/AccessibilityStrategyImplementation.md#accessibility-strategy) and for the [Keyboard Strategy](https://github.com/godbout/kindaVim.docs/blob/master/KeyboardStrategyImplementation.md#keyboard-strategy).

the count for `dd` hasn't been done. so i'll add it to the list. thanks!

**Comment by godbout** [comment]
just gave Smultron a quick look, and it seems that it works out of the box. so probably good macOS AX support. have you had any issue with it? so that i can check quickly for you. thanks.

**Comment by godbout** [comment]
> @godbout Does kindavim support ndd command, such as 3dd? I found only dd works.

added a note in the README about making requests for moves, count, etc. thanks: https://github.com/godbout/kindaVim.docs#current-vim-implementation

**Comment by danny-su** [comment]
> just gave Smultron a quick look, and it seems that it works out of the box. so probably good macOS AX support. have you had any issue with it? so that i can check quickly for you. thanks.

Yes, it works.

**Comment by godbout** [comment]
reopening because this is still need to be added to The Wizard.

**Comment by godbout** [comment]
> @godbout Does kindavim support ndd command, such as 3dd? I found only dd works.

count for dd coming in next release of kV. gonna take some time to build tho. maybe a week or two.

**Comment by godbout** [comment]
Smultron and count for `dd` done in https://github.com/godbout/kindaVim.docs/releases/tag/58
