### ISSUE TITLE
Feature request: Make escape key only enable normal mode

### ISSUE THREAD

**Issue by jstriblet** [godbout/kindaVim.docs#206]
In regular vim I'm used to being able to press escape multiple times (mostly to ensure I'm in normal mode) but when using kinda vim escape cycles between normal mode and input mode and its kinda disorienting.

For example, when I'm in the OSX notes app in insert mode, pressing escape enters normal mode (as expected) however when in normal mode and I press escape again it puts me back into insert mode again (not expected). A setting for keeping in normal mode after multiple escape presses would be much appreciated.

Thanks for this awesome app!

**Comment by godbout** [comment]
> In regular vim I'm used to being able to press escape multiple times (mostly to ensure I'm in normal mode) but when using kinda vim escape cycles between normal mode and input mode and its kinda disorienting.

hahahahahhahahaha maniac hahahahahahahah


> For example, when I'm in the OSX notes app in insert mode, pressing escape enters normal mode (as expected) however when in normal mode and I press escape again it puts me back into insert mode again (not expected). A setting for keeping in normal mode after multiple escape presses would be much appreciated.

hmm. i'm trying to stay as close as Vim's own behavior but yeah. there may have been a reason why currently it works the way it does, but that probably can be fine-tuned now.

what about those Settings:

<img width="693" alt="Screenshot 2023-11-23 at 13 34 22" src="https://github.com/godbout/kindaVim.docs/assets/121373/7702c0b2-0d7a-4f93-8598-66a118eed9fc">

currently `escape` behaves the way you're talking about. but for all the options apart from the `double escape`, i could prevent `escape` to go back to `Insert Mode`? does that make sense?

> Thanks for this awesome app!

welcome. hope you like it. it's in constant development and i'm reachable daily, so please don't hesitate! (to pay and subscribe 😂️😂️😂️)

**Comment by godbout** [comment]
btw how would you go back to `Insert Mode` then? i.e. normal macOS. the usual Vim keys? (`a`, `i`, etc.)

**Comment by jstriblet** [comment]
> what about those Settings:

Yeah, I have tried the other escape options and they sill have the same toggle in and out of insert mode behavior unfortunately. 

> currently escape behaves the way you're talking about. but for all the options apart from the double escape, i could prevent escape to go back to Insert Mode? does that make sense?

That would be awesome! Meaning I could enter normal mode with escape and it wont put me back into insert mode as long as I select one of the other options? (TBH I'm not quite sure what the multiple escape options in the left pick list mean practically)

> (to pay and subscribe 😂️😂️😂️)
Subscribed today 😃

**Comment by jstriblet** [comment]
> btw how would you go back to `Insert Mode` then? i.e. normal macOS. the usual Vim keys? (`a`, `i`, etc.)

Yup, `a`, `i`, `o`, etc

**Comment by godbout** [comment]
> That would be awesome! Meaning I could enter normal mode with escape and it wont put me back into insert mode as long as I select one of the other options?

i need to think and digest what's gonna be the best way to do this. or the way i mentioned above, or adding a new setting. but it's definitely possible to do what you're asking, and i think it'll make kV better overall so i'll implement the feature.

> (TBH I'm not quite sure what the multiple escape options in the left pick list mean practically)

well if you decided to enter Normal Mode with `escape` then kV steals the `escape` key from macOS. now let's say you used to use `escape` to tell Spotlight/Alfred/etc. to back off. but now pressing `escape` enters Normal Mode. how do you back off? well that pick list is there for you to choose what replaces the previous `escape` behavior before kV took over. so rather than pressing `escape` to back off from Alfred, you'd now press `cmd escape` or whatever option you chose.

> > Subscribed today 😃

yes but only for 7 minutes ☹️🥺️

<img width="153" alt="Screenshot 2023-11-23 at 14 54 08" src="https://github.com/godbout/kindaVim.docs/assets/121373/1ed7a174-d4f6-4c45-84a1-82448e6283cc">

😂️😂️😂️

enjoy. will need some time to think and digest, and will keep you updated.

**Comment by jstriblet** [comment]
> well if you decided to enter Normal Mode with escape then kV steals the escape key from macOS..... 

Makes complete sense, got ya!

> yes but only for 7 minutes ☹️🥺️

😂 I wanted to test for a month and see if it helped as much as i though it would (and to my surprise it has). With that + the active dev its probably going to turn into a monthly sub (would love a buy-once-cry-once option though)

**Comment by godbout** [comment]
> 😂 I wanted to test for a month and see if it helped as much as i though it would (and to my surprise it has). With that + the active dev its probably going to turn into a monthly sub (would love a buy-once-cry-once option though)

fair hahahhhahahahahahahah

what i can tell you about this price is 1. it's never gonna be a buy once 2. the price is never gonna go up (well... except if Paddle starts rocketing their fees etc.)

kV can't be a one time. would make no sense. still makes no sense as a one-coffee-a-month sub. it's constant daily work. it's using a fragile part of macOS (AX Framework). and needs constant tests and updates coz there's so many apps to support and that do a shit job. but there's some possible alternatives listed in the README (https://github.com/godbout/kindaVim.docs#alternatives)

i'm gonna do a new release soon and the next next one is gonna be focused on this issue so bear with me a few more days/weeks. still trying to find what's the best way for the long term. thanks!

**Comment by godbout** [comment]
> i'm gonna do a new release soon and the next next one is gonna be focused on this issue so bear with me a few more days/weeks. still trying to find what's the best way for the long term. thanks!

so i've been working on that for the next version and the work is done, including the tests. the issue now is more how to make it make sense through the Settings. still need some thinking and digestion time here.

**Comment by godbout** [comment]
@jstriblet ok so i'm gonna now develop this and the tests properly, and i'll be the main feature in the next release. just wanna confirm that you're still looking forward to this?

**Comment by godbout** [comment]
done in https://github.com/godbout/kindaVim.docs/releases/tag/62
