### ISSUE TITLE
Feature request: please provide multiple ways to enter normal mode

### ISSUE THREAD

**Issue by lubiksss** [godbout/kindaVim.docs#208]
hi i'm kindavim user, and i really thanks to your kindavim

i have a request
i want to enter normal mode using multiple ways
especially i'm korean i want to enter normal mode with
1. press jk sequence
2. press ㅓㅏ sequence

i mean not only korean character sequence, i just want i have multiple sequence way to enter normal mode
thanks to your kindavim, have a nice day

**Comment by godbout** [comment]
it's kinda of tricky because kV **does** provide multiple ways to enter `Normal Mode`: `escape`, a hotkey, or a sequence. i feel if one wants more sequences or hotkeys, then one should use tools that are done for that, like [Karabiner-Elements](https://karabiner-elements.pqrs.org) or [Hammerspoon](https://github.com/Hammerspoon/hammerspoon).

i'll provide some examples of Hammerspoon later where you can just start kV with different sequences.

**Comment by godbout** [comment]
but for the time being i would highly recommend you to check out those two tools cited above:
* https://github.com/pqrs-org/Karabiner-Elements
* https://github.com/Hammerspoon/hammerspoon

KE should be preferred tho as it's a low level keyboard driver, so it's gonna be instant.

**Comment by godbout** [comment]
e.g.: https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/#change-right_shift-x2-to-mission_control

**Comment by lubiksss** [comment]
Thank you for your very kind reply. you have already helped me a lot.

**Comment by godbout** [comment]
i'm reopening coz i haven't finished playing with this yet 😂️😂️😂️

**Comment by godbout** [comment]
second j and d not printed:

```
{:main [

        {
                :des "jk to control command spacebar"
                :rules [
                        [:k :!CTspacebar [:j-pressed]]
                        [
                                :j nil nil
                                {
                                        :alone [:j ["j-pressed" 1]]
                                        :delayed {:invoked ["j-pressed" 0] :canceled ["j-pressed" 0]}
                                }
                        ]
                ]
        },
        {
                :des "df to control command spacebar"
                :rules [
                        [:f :!CTspacebar [:d-pressed]]
                        [
                                :d nil nil
                                {
                                        :alone [:d ["d-pressed" 1]]
                                        :delayed {:invoked ["d-pressed" 0] :canceled ["d-pressed" 0]}
                                }
                        ]
                ]
        }

]}
```

but maybe now you need the first to get removed also when you enter `Normal Mode`? 🤔️

**Comment by godbout** [comment]
no answer for a while. closing. please reopen if needed.
