### ISSUE TITLE
Slack create new line O/o

### ISSUE THREAD

**Issue by Josh-Piper** [godbout/kindaVim.docs#211]
When I hit O or o when in the Slack messaging box it will send the message instead of replicating shift enter to create a new line.

Instead I would expect the O and o to act like it does in a normal text buffer.

**Comment by godbout** [comment]
change this Setting:

<img width="622" alt="Screenshot 2023-11-28 at 12 34 55" src="https://github.com/godbout/kindaVim.docs/assets/121373/b4c4cf25-1267-46fe-9281-55d2cd2e2c1a">

Slack is Electron. most of the Electron apps implement AX support like shit (i think out of 250+ apps i've found only two doing a good job). which means kV can't use text calculations to do the Vim moves. which means kV needs to do key remapping. `enter` is supposed to create a new line on macOS. this is the standard. Slack overrides this. this is why this is happening in your case. change the Setting and `O` and `o` will create the new line.

**Comment by Josh-Piper** [comment]
Amazing, thanks

**Comment by godbout** [comment]
glad it helps!
