### ISSUE TITLE
Please add Tangent

### ISSUE THREAD

**Issue by MananKhattar-at** [godbout/kindaVim.docs#214]
Thank you :)

**Comment by godbout** [comment]
this one right: https://www.tangentnotes.com

**Comment by godbout** [comment]
i can't even launch it LMAO. it freezes

**Comment by godbout** [comment]
first investigation is that this should go to the `Key Mapping` Family. you can add it manually now. i'll add the app to The Wizard.

**Comment by godbout** [comment]
add in kV61: https://github.com/godbout/kindaVim.docs/releases/tag/61
