### ISSUE TITLE
add Noted.app

### ISSUE THREAD

**Issue by gaspardderoyan** [godbout/kindaVim.docs#215]

**Comment by godbout** [comment]
seems there's several apps called Noted, even on the Mac App Store. is this this one: https://apps.apple.com/us/app/noted-record-every-moment/id1446580517?mt=12

thanks

**Comment by godbout** [comment]
from my first investigation Noted seems to be working out of the box. any issue you've encountered?

**Comment by godbout** [comment]
add in kV61: https://github.com/godbout/kindaVim.docs/releases/tag/61
