### ISSUE TITLE
add Heynote

### ISSUE THREAD

**Issue by MananKhattar-at** [godbout/kindaVim.docs#218]
https://heynote.com/. Thank you!

**Comment by godbout** [comment]
will do. thanks! your other request(s) is on the way. expecting a kV release soon.

**Comment by godbout** [comment]
first investigation shows this needs to be put in the `Key Mapping` Family. coming to next kV's release.

**Comment by godbout** [comment]
add in kV61: https://github.com/godbout/kindaVim.docs/releases/tag/61
