### ISSUE TITLE
Cannot Move Upwards with J Key 

### ISSUE THREAD

**Issue by dlahmad** [godbout/kindaVim.docs#220]
Hi,
I have the problem that I cannot move upwards in Text Fields in Firefox, Teams and WA.

When I press the **K** key I move down correctly, but with the **J** I do not move up and it seems to be registered as an **a** key press. I am using an englisch US layout. 

Could this be a bug?

Best regards

**Comment by godbout** [comment]
ok, first:

> When I press the **K** key

you mean `k`? lowercase? `K` is not related to moving.

> I move down correctly

? `k` is up lol

> but with the **J**

you mean `j`? lowercase? `J` joins lines.

> I do not move up

ok but `j` is supposed to move down 

> and it seems to be registered as an **a** key press. I am using an englisch US layout.

weird

> Could this be a bug?

in kV most probably no, not on those moves. 

1. last time i checked Firefox was still shit with supporting the macOS AX so you had to add it to the `Key Mapping` Family. have you done that? see https://github.com/godbout/Wooshy.docs/issues/125
2. Teams, which one. old classic or new shit?
3. what is WA?

**Comment by dlahmad** [comment]
Yes, my bad.

I mean both lower case variants and you are right j is down.

1. I added firefox to that, but the problem remains.
2. Teams Classic
3. WhatsApp (Electron APP)

The problem seems to be that it interprets my "j" as an "a" for whatever reason.

**Comment by dlahmad** [comment]
Actually I just found the issue. It was a weird interaction between the [VIMSpoon](https://github.com/dbalatero/VimMode.spoon) and your tool, although I do not know why it works like that. After killing HammerSpoon, it works as expected.

**Comment by godbout** [comment]
> Yes, my bad.

agreed. HHAHHAHAHAHAHAHAHAH

> 3. WhatsApp (Electron APP)

why are you using the Electron version? they've released a new version that is native if i remember well. works much better with kV.

**Comment by godbout** [comment]
> Actually I just found the issue. It was a weird interaction between the [VIMSpoon](https://github.com/dbalatero/VimMode.spoon) and your tool, although I do not know why it works like that. After killing HammerSpoon, it works as expected.

oh. so it's probably something that takes over in your hammerspoon config. try commenting parts of the config and see what's going on.

**Comment by dlahmad** [comment]
Yeah, in any case, thanks a lot. I will sort that out on my own.

**Comment by godbout** [comment]
post your config and let’s have a quick look together
