### ISSUE TITLE
Special vim mode for arc browser

### ISSUE THREAD

**Issue by dwbutler** [godbout/kindaVim.docs#221]
The various shortcuts in Arc Browser are super confusing for me to remember. And they often interfere with OS shortcuts. Similar to my experience with emacs. I would like the option for a vim-style “normal” mode in which commands can be quickly typed, autocompleted, and interpreted to perform actions for me.

**Comment by godbout** [comment]
sorry, i don't get what you mean. will try to dissect:

> The various shortcuts in Arc Browser are super confusing for me to remember

that's an Arc issue right? not kV.

> And they often interfere with OS shortcuts.

again, Arc issue>

> I would like the option for a vim-style “normal” mode in which commands can be quickly typed, autocompleted, and interpreted to perform actions for me.

do you mean specifically for Arc? i'm not sure if you're asking for more [commands](https://github.com/godbout/kindaVim.docs/blob/master/CommandsImplementation.md#commands) handled by kV, or somehow that kV "controls" Arc?

**Comment by godbout** [comment]
no answer for six months. closing. please reopen if needed.
