### ISSUE TITLE
"daw" now working, and if you type "daw" first and later the "dw" turns out not working any more.

### ISSUE THREAD

**Issue by arglin** [godbout/kindaVim.docs#223]

**Comment by godbout** [comment]
wot?

**Comment by godbout** [comment]
which app? is kV using the Accessibility Strategy (block cursor) or the Keyboard Strategy (normal macOS cursor)?

**Comment by godbout** [comment]
coz as you can see below it works fine here:

https://github.com/godbout/kindaVim.docs/assets/121373/a4d7a535-c8d6-4f2d-8edf-456f81f0f4a6

when the text is accessible, the motions are laser good. so might be you're using the Keyboard Strategy on a shit app. lemme know and i'll check.

**Comment by godbout** [comment]
no answer for six months so closing. please reopen if needed.
