### ISSUE TITLE
not working on neovide

### ISSUE THREAD

**Issue by haveanicedavid** [godbout/kindaVim.docs#224]
Trying to set up [neovide](https://neovide.dev) for neovim, and kV doesn't seem to honor ignore rules. Any way I can help troubleshoot?

EDIT: Apologies I didn't search past issues - just realized this has been addressed before. Closing

**Comment by godbout** [comment]
no worries. that was a tricky one. and the whole thread is worth reading actually, very funny i think 😂️😂️😂️ https://github.com/godbout/kindaVim.docs/issues/119

i miss those nights drunk working deeply on kV for hours 😥️ (but doing the same studying some stuff now)

have a nice day... vid.
