### ISSUE TITLE
add Homerow

### ISSUE THREAD

**Issue by plasmadice** [godbout/kindaVim.docs#226]
[Homerow](https://www.homerow.app/)

Would add to `Off` category.

**Comment by godbout** [comment]
ahhahhahahhhahahah [Wooshy](https://github.com/godbout/Wooshy.docs)'s little brother hahahahhahaha

why on the `Off` tho? is kV disturbing Homerow somehow? should be useful for those who use the search bar.

**Comment by godbout** [comment]
done in kV63: https://github.com/godbout/kindaVim.docs/releases/tag/63
