### ISSUE TITLE
not working on Arc

### ISSUE THREAD

**Issue by ajdubovoy** [godbout/kindaVim.docs#227]
The moves actually work ok, but the problem is that, when I'm in full screen mode (which is usually how I use it), enabling kindaVim dims the browser window, even though it's the active window.

**Comment by godbout** [comment]
set the `Highlight the window that is Viming:` to the max left for the `fullscreen opacity` setting:

![Screenshot 2024-03-20 at 19 15 15](https://github.com/godbout/kindaVim.docs/assets/121373/65aca7e7-058f-4133-8d8c-f6e604bde412)

it's been noted in [here](https://github.com/godbout/kindaVim.docs/issues/217) that the name of the setting is kinda confusing. the idea was to "highlight" as in "make stand out". when you're not in fullscreen the way to make the current kV's recipient stand out is to darken what's around, but in fullscreen... you can't darken what's around, so instead kV adds a layer on top of the whole fullscreen app. but as shown above, you can just totally remove it hehe. hope that's clear.

**Comment by ajdubovoy** [comment]
Oh ok, done, thank you!
