### ISSUE TITLE
add Notable

### ISSUE THREAD

**Issue by danny-su** [godbout/kindaVim.docs#228]
https://github.com/notable/notable

**Comment by godbout** [comment]
will investigate. thanks

**Comment by godbout** [comment]
from what i understand it's an Electron app, but it doesn't respond to my injunctions of enabling its AX Tree. posted here: https://github.com/notable/notable/issues/1726

will see what they say. more on this later.

**Comment by godbout** [comment]
from what i see currently it should go into the `Key Mapping` Family. lemme know if you have any issue when added into that Family. will update The Wizard in the next release.

**Comment by godbout** [comment]
done in kV63: https://github.com/godbout/kindaVim.docs/releases/tag/63
