### ISSUE TITLE
Off mode gobbling up trigger sequence

### ISSUE THREAD

**Issue by pekcheey** [godbout/kindaVim.docs#231]
I'm on Mac using MacVim. 
I've set the activation shortcut on KindaVim to "⌃["

It works fine generally except in MacVim. Seems like KindaVim gobbled up the "⌃[" shortcut so that I'm not able to use the  keystroke within MacVim itself.

I believe that the correct way to handle this would be to allow the shortcut to pass through to the underlying application.

**Comment by godbout** [comment]
definitely sounds like a bug 🤔️ 
hmm rings a bell actually. the bypassing not working with the Custom Shortcut. but that was fixed. or maybe it was something similar. anyways, will check, thanks!

**Comment by godbout** [comment]
so:
1. can reproduce
2. i can't find any reference of this issue in the past, and yet I"M SURE someone mentioned and i had confirmed and fixed it. but seems it was all a dream. also pretty sure it was obvious in Vim in Terminal/iTerm. life is weird. anyways, a fix will come very soon.

**Comment by godbout** [comment]
@pekcheey ok so on my Air when i tried to reproduce this morning i was able to. on my mini tonight trying to debug i couldn't lol. seems this happens only after you've set the Custom Shortcut. if you restart kV then it's working fine. can you confirm?

**Comment by pekcheey** [comment]
oh yes. you are right. the problem went away after restarting kV.  Since there is a work around, I'm okay with closing this issue should you want to.  Thanks.

**Comment by godbout** [comment]
nah nah nah nah nah. that's definitely a bug. and bad UX for cases like yours. should not happen very often but still. as soon as you'll change the Custom Shortcut that'll happen again until kV is restarted. so yeah, needs to be fixed. thanks for reporting!

**Comment by godbout** [comment]
fixed in kV63: https://github.com/godbout/kindaVim.docs/releases/tag/63
