### ISSUE TITLE
kindavim.app appears to be down

### ISSUE THREAD

**Issue by Lontronix** [godbout/kindaVim.docs#233]
Been really enjoying kindavim and wanted to subscribe but it seems like the website is down 😢

**Comment by godbout** [comment]
also:

<img width="664" alt="Screenshot 2024-04-11 at 01 09 59" src="https://github.com/godbout/kindaVim.docs/assets/121373/9059537d-9f2f-4df6-9f92-e1aa7e1b3125">

**Comment by godbout** [comment]
servers are in Singapore. any reason why you wouldn't be able to access those?

**Comment by Lontronix** [comment]
Its working now but I'm on a different wifi network... Wonder if maybe it was being blocked no the public wifi I was on.

Sorry about that!

**Comment by godbout** [comment]
kV is so good that it scares some network yeah!
