### ISSUE TITLE
add Anki

### ISSUE THREAD

**Issue by Brandon-Lu737** [godbout/kindaVim.docs#234]
When I'm editing a card, this doesn't work at all `j`, `k`, `w`, etc.

<img width="1294" alt="image" src="https://github.com/godbout/kindaVim.docs/assets/107624116/aa07558a-e503-44fb-90da-c4465741cc0a">

Look at the textbook on the right
```
judicial review
{{c1:: the power of a court to declare an act of government (or action of a government official) unconstitutional }}
```

Thank you!

**Comment by godbout** [comment]
might look like Java. gonna be touch. i'll investigate. and i'll add the results of the investigation in the next release that should come out the coming weekend.

for the time being try to add the app to different `Families` in The Wizard (Settings) and see how it changes. the `911` should work for sure. (although the moves are done with key remapping so it's a little funky sometimes.)

**Comment by godbout** [comment]
done in kV63: https://github.com/godbout/kindaVim.docs/releases/tag/63
