### ISSUE TITLE
add Microsoft Teams (work or school).app

### ISSUE THREAD

**Issue by vidomark** [godbout/kindaVim.docs#238]

**Comment by godbout** [comment]
same. will do. i'l planning for an imminent release. see if i can add them in.

**Comment by vidomark** [comment]
Appreciate it.

Wanted to say that the app is amazing. Thank you for doing this.😊

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by godbout** [comment]
my pleasure. as i've stated it here many times, i'm doing this for myself 😂️😂️😂️ macOS user i am for my day to day, love and need my Vim motions, so kV is here to stay. that being said, it's complicated to "wrap" all the different apps to get some sort of unified UX, so as you'll see (or saw), even though kV is trying its best, it's still has some rough edges. but the development is continuous, so we'll do what we can to have the best Vim experience on macOS as we can ✌️

**Comment by godbout** [comment]
done in kV63: https://github.com/godbout/kindaVim.docs/releases/tag/63
