### ISSUE TITLE
add Spyder

### ISSUE THREAD

**Issue by danny-su** [godbout/kindaVim.docs#240]
https://www.spyder-ide.org

**Comment by godbout** [comment]
will do. thanks.

**Comment by godbout** [comment]
as far as my tests go, Spyder needs to be in the `PGR` Family, at least for the editor to work properly. some moves will not work nicely in the Console tho. not sure why but they're not using the same system for the two Text Areas.

for Text Editors it's 99% of the time better to use their own Vim plugins, coz they own their own buffer and provide all the info needed to their own plugin systems, which they can't (don't) do to the whole macOS. there seems to be quite a few, like:
* https://github.com/spyder-ide/spyder-vim
* https://github.com/ok97465/spyder_okvim

**Comment by godbout** [comment]
added in kV64: https://github.com/godbout/kindaVim.docs/releases/tag/64
