### ISSUE TITLE
add RazorSQL

### ISSUE THREAD

**Issue by danny-su** [godbout/kindaVim.docs#241]

**Comment by godbout** [comment]
coming in next release. planning for this week. thanks.

**Comment by godbout** [comment]
Java app. nightmare regarding AX. if you wanna move around add it to the `911` Family. but you still can't delete/etc. probably best is just to put it in the `Off` Family.

**Comment by godbout** [comment]
added in kV64: https://github.com/godbout/kindaVim.docs/releases/tag/64
