### ISSUE TITLE
add The Archive

### ISSUE THREAD

**Issue by mk1123** [godbout/kindaVim.docs#245]
thanks :)

**Comment by godbout** [comment]
will do. thanks!

**Comment by godbout** [comment]
@mk1123 did some tests. The Archive works beautifully out of the box so you don't need to add it to any Family. i'll add it to The Wizard for the next release. thanks!

**Comment by godbout** [comment]
added in kV66: https://github.com/godbout/kindaVim.docs/releases/tag/66
