### ISSUE TITLE
add XTerminal

### ISSUE THREAD

**Issue by danny-su** [godbout/kindaVim.docs#248]

**Comment by godbout** [comment]
starting digging into this. not sure what XTerminal you're talking about.

* XTerminal for the web??? https://xterminal.js.org/demo.html
* xTerminal for iOS??? https://apps.apple.com/mo/app/xterminal-ssh-terminal-shell/id1544728400?l=en-GB

**Comment by danny-su** [comment]
@godbout https://xterminal.cn/

**Comment by godbout** [comment]
:kiss: :kiss:

**Comment by godbout** [comment]
added in kV66: https://github.com/godbout/kindaVim.docs/releases/tag/66
