### ISSUE TITLE
Not entering insert mode on sequence (jj) without a modifier key.

### ISSUE THREAD

**Issue by nicholasrq** [godbout/kindaVim.docs#253]
Experiencing quite a weird behavior with entering Insert mode. My kV is set up with `jj` to go to insert and using just the sequence doesn't work at all.

For some reason it only works in combination with any Cmd/Ctrl held. I'am pretty sure it's some software messing with it, not sure what, though.

I have Karabiner and Hammerspoon installed, though they barely have anything set up. I also tried disabling both, no luck.

Another thing is that I use Colemak DH. Not sure if that's the reason as it still works (with a modifier ¯\_(ツ)_/¯).

Any ideas? What else to check/disable?

**Comment by godbout** [comment]
> Experiencing quite a weird behavior with entering Insert mode. My kV is set up with `jj` to go to insert and using just the sequence doesn't work at all.
> 
> For some reason it only works in combination with any Cmd/Ctrl held. I'am pretty sure it's some software messing with it, not sure what, though.

hmm. working fine here. so yeah it seems it could be something fucking with your system.
 
> I have Karabiner and Hammerspoon installed, though they barely have anything set up. I also tried disabling both, no luck.

that's what i would have suggested. trying without them first. any other tool you have? like BTT? some users had stuff in BTT that was messing keys before kV handles them.

> Another thing is that I use Colemak DH. Not sure if that's the reason as it still works (with a modifier ¯_(ツ)_/¯).

probably a stupid question but, that Colemak DH is a software keyboard layout right? if yes then lemme know exactly which one and i'll see if i can reproduce here. would help a lot.

**Comment by nicholasrq** [comment]
@godbout ty for a quick reply!

I have Karabiner (disabled now) and Hammerspoon. the latter is fresh installed and I didn't have it until recently, tho the issue was here. no BTT. had skhd, but uninstalled yesterday, the issue persist. another thing I have is Aerospace(TWM), but again, issues was here before I installed it

speaking of Colemak, I installed it from [here](https://colemakmods.github.io/mod-dh/). however, i previously had it set up on my keyboard directly, yet issue is here despite that

probably, will be disabling apps one by one to see what's messing with the system because when I just installed kK few months ago, it was perfectly fine

**Comment by godbout** [comment]
> @godbout ty for a quick reply!

i'm here everyday!

> speaking of Colemak, I installed it from [here](https://colemakmods.github.io/mod-dh/). however, i previously had it set up on my keyboard directly, yet issue is here despite that

so how did you install it? [cross-platform](https://github.com/ColemakMods/mod-dh?tab=readme-ov-file#cross-platform-windows-linux-mac) or the [macOS way](https://github.com/ColemakMods/mod-dh/tree/master/macOS)

> probably, will be disabling apps one by one to see what's messing with the system because when I just installed kK few months ago, it was perfectly fine

what if you choose another sequence? does that sequence work?
what about `esc`? and the `custom shortcut` way?

i think all i can do for now is asking you question and see if i get an idea on **kV**'s side. i'd be surprised but you never know.

**Comment by nicholasrq** [comment]
@godbout 

> so how did you install it? [cross-platform](https://github.com/ColemakMods/mod-dh?tab=readme-ov-file#cross-platform-windows-linux-mac) or the [macOS way](https://github.com/ColemakMods/mod-dh/tree/master/macOS)

macOS way, didn't want to mess with kmonad

> what if you choose another sequence? does that sequence work?
> what about esc? and the custom shortcut way?

`esc` works just fine. checked two other sequences (`ne`, `lu`), works as expected o_O. now I'm even more confused

> i think all i can do for now is asking you question and see if i get an idea on kV's side. i'd be surprised but you never know.

I highly doubt it's kV's problem, rather a weird collision between it and something on my mac. I will experiment with it further and will post here if found anything

**Comment by godbout** [comment]
> macOS way, didn't want to mess with kmonad

alright. will check and keep you updated.

> `esc` works just fine. checked two other sequences (`ne`, `lu`), works as expected o_O. now I'm even more confused

what's funny to me is why you didn't try a sequence that starts with `j` 🤣️🤣️🤣️
see why below.

> I highly doubt it's kV's problem, rather a weird collision between it and something on my mac. I will experiment with it further and will post here if found anything

i'm thinking. could it be possible that you're having an app, for example like something that does snippet expansion on macOS, that messes up the keystrokes stream? maybe like with some snippets that start with `j`? and with a too long delay for catching up the following keys? (kinda making stuff up from now on lol)

**Comment by nicholasrq** [comment]
> alright. will check and keep you updated.
tried US layout, `jj` still doesn't work

> what's funny to me is why you didn't try a sequence that starts with j 🤣️🤣️🤣️
fair enough :D tried `jl`, works as well. so it'r only `jj` that does it's weird thingie

> i'm thinking. could it be possible that you're having an app, for example like something that does snippet expansion on macOS, that messes up the keystrokes stream? maybe like with some snippets that start with j? and with a too long delay for catching up the following keys? (kinda making stuff up from now on lol)

I tried shutting down everything yesterday, no luck so far

I also just tried increasing the delay in kV to 200ms it definitely picks up the first press as I see a noticeable delay between pressing `j` and the output of the keypress in any text field

**Comment by nicholasrq** [comment]
@godbout woah, I just found that the built-in keyboard works (i use external one most of the time). I thought that it might be that my keyboard don't like quickly repeating characters, so I tried mapping kV to something like `ll`. and it works. gonna dig into my qmk config now. not sure what it could be though

**Comment by nicholasrq** [comment]
idk what to think now. it suddenly started working just fine and I don't know why. here are the steps I took, though I'm not sure why could it've helped

- changed layout to US
- set delay to 200ms
- set sequence to `jj`
- tried the sequence with US layout on built-in keeb (worked)
- switched back to colemak
- tried the sequence with Colemak on built-in keeb (worked)
- tried the sequence on external keyboard (worked)
- tried previous step for ~20 times, worked every time

tf is going on

**Comment by godbout** [comment]
> tf is going on

i live in China and today's Chinese National Day. is that good enough of an explanation?

> set delay to 200ms

what about a lower delay?

> tried previous step for ~20 times, worked every time

so does that mean that if you don't do those steps, it's not working???

**Comment by nicholasrq** [comment]
> i live in China and today's Chinese National Day. is that good enough of an explanation?
unless we have a better one, I guess ¯\_(ツ)_/¯ 

> what about a lower delay?
it seems to be working, but apparently my fingers are not fast enough to work with <130ms delay (though I had 80ms initially). one thing came to my mind is that I was on qwerty back then and `j` was right under my index finger, so I could rapidly press it. now on Colemak it's in the top left corner, so I can't apply the same force/speed when pressing it

> so does that mean that if you don't do those steps, it's not working???
I'm not sure already -_-. It's been working as expected since yesterday. I'm curious what would happen if I restart the machine though. Gonna find out today after the upgrade to Sequoia.

anyway, thank you for the assistance. I will see how it works during next few days before closing this issue, if you don't mind. just in case it breaks again

**Comment by godbout** [comment]
> it seems to be working, but apparently my fingers are not fast enough to work with <130ms delay (though I had 80ms initially). one thing came to my mind is that I was on qwerty back then and `j` was right under my index finger, so I could rapidly press it. now on Colemak it's in the top left corner, so I can't apply the same force/speed when pressing it

the whole thing is just gonna be about your fingers being too slow lmao

> I'm not sure already -_-. It's been working as expected since yesterday. I'm curious what would happen if I restart the machine though. Gonna find out today after the upgrade to Sequoia.

can't wait.

> anyway, thank you for the assistance. I will see how it works during next few days before closing this issue, if you don't mind. just in case it breaks again

my pleasure. i'm having a lot of fun and meaning. we keep it open until the last resort is to call Tim Apple

**Comment by godbout** [comment]
@nicholasrq how is it going? still need or we can close?

**Comment by godbout** [comment]
no answer is good answer. closing. please reopen if needed.
