### ISSUE TITLE
Cant enter normal mode with MacOS Sonoma 14.6

### ISSUE THREAD

**Issue by ghaarm** [godbout/kindaVim.docs#255]
Hi,

First of all thanks for your great work! Got a subscription this month and I really like kindaVim on a Mac with Ventura 13.6.9.

I changed to Sonoma 14.6 though. I can start kindaVim but when I enter my sequence (jk 150 ms) just nothing happens - well except that I write jk in the app that is currently open.

Anyone has similar problems?

Thanks and best regards.

**Comment by godbout** [comment]
> Hi,

HELLO

> First of all thanks for your great work! Got a subscription this month and I really like kindaVim on a Mac with Ventura 13.6.9.

you're welcome. and thanks.

> I changed to Sonoma 14.6 though. I can start kindaVim but when I enter my sequence (jk 150 ms) just nothing happens - well except that I write jk in the app that is currently open.

kV should work from Monterey to Sequoia. there's a [bug in macOS](https://github.com/feedback-assistant/reports/issues/390) that affects all apps that use an event tap and requires a reboot. apart from this things should be ok. so:

1. can you reboot and see?
2. can you push the sequence to the max (200ms) and see?
3. what about if you change to entering with escape, or a custom shortcut. does kV enter Normal Mode?

**Comment by ghaarm** [comment]
Hi,

thanks for your fast reply! Reboot did it! Now its working again.

>     2. can you push the sequence to the max (200ms) and see?

Tried that before I commented on github (and before reboot), but also with 200 ms it wasn't working.

>     3. what about if you change to entering with escape, or a custom shortcut. does kV enter Normal Mode?

Tried that before I commented on github (and before reboot), but also with esc it wasn't working.

Cheers and have a nice weekend!

**Comment by godbout** [comment]
> Hi,

HELLO

> thanks for your fast reply! Reboot did it! Now its working again.

n🧊️

> Tried that before I commented on github (and before reboot), but also with 200 ms it wasn't working.
> Tried that before I commented on github (and before reboot), but also with esc it wasn't working.

yeah so that's the macOS bug (reported as FB12113281). Apple still hasn't fixed it. it may happen to you a couple of times a year, if you're unlucky. all we can do is reboot. it affects all the apps that need to use an event tap to catch keystrokes. kV is impacted (Wooshy and Scrolla are not), as well as for example all the snippet managers (Dash, Alfred etc.). there's nothing else we can do expect pinging Apple every year.

> Cheers and have a nice weekend!

THANK YOU YOU TOO TYPHOON NUMBER 3 HERE THO

have fun with kV
