### ISSUE TITLE
add iPhone Mirroring.app

### ISSUE THREAD

**Issue by jannis-baum** [godbout/kindaVim.docs#256]
I almost feel bad for asking this because it's probably a nightmare but here u go :p

**Comment by godbout** [comment]
hardest is gonna be to make that shit work lol. "connection interrupted". "timeout". 😴️😴️😴️
no idea about kV yet but at least Wooshy can catch the "try again" buttons 🤣️🤣️🤣️

**Comment by godbout** [comment]
completely inaccessible. Wooshy can't do anything either once the iPhone has been loaded. Scrolla is slow, and `G` makes the whole app crash lol

so yeah, iPhone Mirroring to the Off Family. will add it to The Wizard in the next release.

**Comment by jannis-baum** [comment]
> hardest is gonna be to make that shit work lol. "connection interrupted". "timeout". 😴️😴️😴️
> 
> no idea about kV yet but at least Wooshy can catch the "try again" buttons 🤣️🤣️🤣️

Hahah yeah, definitely not nearly as smooth as it looked in the keynote😂 every time I see that loading screen I debate if it's better to wait for it or to go grab my phone lol

**Comment by godbout** [comment]
done in https://github.com/godbout/kindaVim.docs/releases/tag/67
