### ISSUE TITLE
BUG can't acces normal mode

### ISSUE THREAD

**Issue by Friedolito** [godbout/kindaVim.docs#257]
Hey thank you for creating kindaVim. 

There seems to be a bug going on for me.
Intering normal mode I can't use motions and there is a half hidden pop up appearing on my screen. 

kindaVim is on the current version 
macOS Sequoia 15.2

Happy for a fix! 
Best regards :) 

![Screenshot -2024-12-16 at 08 20 36](https://github.com/user-attachments/assets/7123b2a3-a4da-4166-990a-8afedc9834f2)

**Comment by godbout** [comment]
hahahahhahha sounds like a troll but fine. 

see https://github.com/godbout/kindaVim.docs

between 5am and 1pm (the time i was sleeping when building kV) kV is sleeping if you don’t have a license. hence the pop up. the pop up shows in the wrong place and half eaten up because you’re using an app that tweaks the menu bar and is pushing kV’s menu bar icon out of the screen.

to enjoy kV fully you can 1) using it between 1pm and 5am 2) treat kV one coffee a month (or twelve coffees a year)

enjoy!

**Comment by Friedolito** [comment]
:D No I was genuinely concerned! 
Ah good to know, thanks!

**Comment by godbout** [comment]
> :D No I was genuinely concerned!

sorry. power of habit. too many people trashing the non-open source and the sub payment system. hehe. my apologies

@Friedolito FWIW there's an open issue (and i think many closed ones) regarding the kV's licensing system: https://github.com/godbout/kindaVim.docs/issues/232. it's a very fair "complaint". i'm planning to do something better, but i'm not sure what yet. 1) i abhor working in the payment/licensing system. i'd gladly give 30% to Apple if they accepted my apps on the macOS App Store 2) it's hard to find a way to prevent people to just delete some file and being able to bypass a trial. believe me, my DMS tell me there's many angry cheapfucks out here lol. that don't wanna pay but want support (and see the [number of releases](https://github.com/godbout/kindaVim.docs/releases), kV is HIGHLY active). anyways, just to say that it's not lost on me that the current experience is not ideal, and i'll hopefully come with a better one. but it's also not a priority. (would rather add some new motions woohooohooh. cheers.)

**Comment by godbout** [comment]
> Yea. I actually uninstalled when this payment request system came up. It was concerning to me and felt like malware. I'm glad to know its just a request for compensation.

kindaVim is a paid app: https://kindavim.app/#buy
