### ISSUE TITLE
Can't test the app between 5am and 1pm without a License

### ISSUE THREAD

**Issue by abhibeckert** [godbout/kindaVim.docs#90]
What's with the "sleepy mode" and there being no way to test the app out prior to 1pm?

Is there a refund if I decide I don't like it after paying? I generally only work mornings.

**Comment by godbout** [comment]
> What's with the "sleepy mode" and there being no way to test the app out prior to 1pm?

might be a bug. or might be the fact that it's a PAID APP: https://github.com/godbout/kindaVim.theapp#license
some apps offer full trial for 7 days. or 30 days. then you can't use the app anymore without a license. with kV there's no limit. but if you want to use it from 5am to 1pm, you need a license. for the rest of the time you don't need a license. forever.

> Is there a refund if I decide I don't like it after paying? I generally only work mornings.

kV is a one man show. that is to say, anything is possible. if somehow you're not able to be conscious for the other 16 hours (between 1pm and 5am) let me know and we'll find something.

**Comment by godbout** [comment]
i'll be editing the title, to reflect reality.
