### ISSUE TITLE
add Superhuman

### ISSUE THREAD

**Issue by dudunato** [godbout/kindaVim.docs#91]

**Comment by godbout** [comment]
i had a look, but if i get this correctly it's 1) a 30US a month app 2) there's no trial 3) it's on invite? 😅️

from the bundle name it seems it's an Electron app. you been using kV with it? how bad is it? can you describe and/or maybe send a screencast?

i'll see what i can do on my side. thanks.

**Comment by godbout** [comment]
Superhuman was added in kV29: https://github.com/godbout/kindaVim.docs/releases/tag/29
